export const E_WALLETS = ["GCash", "Maya"];
export const PHILIPPINES_BANKS = [
  "Asia United Bank (AUB)",
  "Bank of Commerce",
  "Bank of the Philippine Islands (BPI)",
  "BDO Unibank",
  "China Banking Corporation (Chinabank)",
  "Citibank Philippines",
  "Development Bank of the Philippines (DBP)",
  "EastWest Bank",
  "HSBC Philippines",
  "Land Bank of the Philippines (Landbank)",
  "Maybank Philippines",
  "Metropolitan Bank & Trust Company (Metrobank)",
  "Overseas Filipino Bank (OFBank)",
  "Philippine Bank of Communications (PBCom)",
  "Philippine National Bank (PNB)",
  "Philippine Savings Bank (PSBank)",
  "Rizal Commercial Banking Corporation (RCBC)",
  "Robinsons Bank",
  "SeaBank Philippines",
  "Security Bank",
  "Sterling Bank of Asia",
  "Tonik Digital Bank",
  "UCPB Savings Bank",
  "UNO Digital Bank",
  "Union Bank of the Philippines (UnionBank)",
];
export const PAYMENT_OPTION = {
  E_WALLET: { id: "E_WALLET", label: "E-Wallet" },
  CASH: { id: "CASH", label: "Cash" },
  BANK_TRANSFER: { id: "BANK_TRANSFER", label: "Bank Transfer" },
};

export const PAYMENT_OPTIONS = [
  PAYMENT_OPTION.E_WALLET,
  PAYMENT_OPTION.BANK_TRANSFER,
  PAYMENT_OPTION.CASH,
];

export const DB_METHOD_STATUS = {
  SUCCESS: "success",
  ERROR: "error",
};

export const DB_COLLECTION = {
  USERS: "users",
  STORES: "stores",
  PRODUCTS: "products",
  RECEIPTS: "receipts",
  PRODUCT_CATEGORIES: "product_categories",
  INVENTORY: "inventory",
  ORDERS: "orders",
  SETTINGS: "settings",
};

export const OPTIONS_HOUR = Array.from({ length: 12 }, (_, index) => {
  const hour = index + 1; // Generates numbers from 1 to 12
  return {
    value: hour.toString(),
    label: `${hour}`,
  };
});

export const OPTIONS_MINUTE = Array.from({ length: 12 }, (_, index) => {
  const minute = index * 5; // Generates 0, 5, 10, ..., 55
  return {
    value: minute.toString().padStart(2, "0"), // Ensures two-digit format
    label: minute.toString().padStart(2, "0"),
  };
});

export const PH_PROVINCES: string[] = [
  "Abra",
  "Agusan del Norte",
  "Agusan del Sur",
  "Aklan",
  "Albay",
  "Antique",
  "Apayao",
  "Aurora",
  "Basilan",
  "Bataan",
  "Batanes",
  "Batangas",
  "Benguet",
  "Biliran",
  "Bohol",
  "Bukidnon",
  "Bulacan",
  "Cagayan",
  "Camarines Norte",
  "Camarines Sur",
  "Camiguin",
  "Capiz",
  "Catanduanes",
  "Cavite",
  "Cebu",
  "Cotabato",
  "Davao de Oro",
  "Davao del Norte",
  "Davao del Sur",
  "Davao Occidental",
  "Davao Oriental",
  "Dinagat Islands",
  "Eastern Samar",
  "Guimaras",
  "Ifugao",
  "Ilocos Norte",
  "Ilocos Sur",
  "Iloilo",
  "Isabela",
  "Kalinga",
  "La Union",
  "Laguna",
  "Lanao del Norte",
  "Lanao del Sur",
  "Leyte",
  "Maguindanao del Norte",
  "Maguindanao del Sur",
  "Marinduque",
  "Masbate",
  "Misamis Occidental",
  "Misamis Oriental",
  "Mountain Province",
  "Negros Occidental",
  "Negros Oriental",
  "Northern Samar",
  "Nueva Ecija",
  "Nueva Vizcaya",
  "Occidental Mindoro",
  "Oriental Mindoro",
  "Palawan",
  "Pampanga",
  "Pangasinan",
  "Quezon",
  "Quirino",
  "Rizal",
  "Romblon",
  "Samar",
  "Sarangani",
  "Siquijor",
  "Sorsogon",
  "South Cotabato",
  "Southern Leyte",
  "Sultan Kudarat",
  "Sulu",
  "Surigao del Norte",
  "Surigao del Sur",
  "Tarlac",
  "Tawi-Tawi",
  "Zambales",
  "Zamboanga del Norte",
  "Zamboanga del Sur",
  "Zamboanga Sibugay",
];